/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: GFD.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @GFD: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("firstOption", () => this.@firstOption, val => this.@firstOption = val);
			VarDef("secondOption", () => this.@secondOption, val => this.@secondOption = val);
			VarDef("thirdOption", () => this.@thirdOption, val => this.@thirdOption = val);
		}

		public StoryVar @firstOption;
		public StoryVar @secondOption;
		public StoryVar @thirdOption;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@GFD()
	{
		this.StartPassage = "beemoIntroduce";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: beemoIntroduce

	void passage1_Init()
	{
		this.Passages[@"beemoIntroduce"] = new StoryPassage(@"beemoIntroduce", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Привет, путешественник! ");
		yield return lineBreak();
		yield return text("Надеюсь для тебя уже стало очевидно, что ты заперт на этой поляне. Для того, чтоб" +
		    "ы выбраться, тебе придётся пройти мою игру. Сейчас расскажу как мной пользоватьс" +
		    "я.");
		yield return lineBreak();
		yield return link("Начать обучение", "beemoStartTutorial", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #2: beemoStartTutorial

	void passage2_Init()
	{
		this.Passages[@"beemoStartTutorial"] = new StoryPassage(@"beemoStartTutorial", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Я расскажу тебе историю, но её исход зависит только от тебя. Ты можешь делать выб" +
		    "ор, нажимая на кнопки, которые появляются под экраном. Попробуй нажать.");
		yield return lineBreak();
		yield return link("Попробовать", "beemoMoney", null);
		yield return text("\t");
		yield return lineBreak();
		yield return link("Попробовать", "beemoMoney", null);
		yield return lineBreak();
		yield return link("Открыть выход", "beemoHahaMoney", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #3: beemoMoney

	void passage3_Init()
	{
		this.Passages[@"beemoMoney"] = new StoryPassage(@"beemoMoney", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("В дальнейшем, чтоб сделать выбор, тебе необходимо будет платить монетами. Их коли" +
		    "чество отображается в верхней части моего экрана.");
		yield return lineBreak();
		yield return link("Понятно", "beemoGoToRunTutorial", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #4: beemoHahaMoney

	void passage4_Init()
	{
		this.Passages[@"beemoHahaMoney"] = new StoryPassage(@"beemoHahaMoney", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Ха-ха-ха! ");
		yield return lineBreak();
		yield return text("Ты и правда думал, что я так просто тебя отпущу? ");
		yield return lineBreak();
		yield return text("Забудем про твою попытку побега и вернемся к обучению. ");
		yield return lineBreak();
		yield return text("В дальнейшем, чтоб сделать выбор, тебе необходимо будет платить монетами. Их коли" +
		    "чество отображается в верхней части моего экрана.");
		yield return lineBreak();
		yield return link("Понятно", "beemoGoToRunTutorial", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #5: beemoGoToRunTutorial

	void passage5_Init()
	{
		this.Passages[@"beemoGoToRunTutorial"] = new StoryPassage(@"beemoGoToRunTutorial", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Заработать их ты сможешь, потратив самое дорогое, что у тебя есть!");
		yield return lineBreak();
		yield return text("Нажимай на кнопку \"Добыть монеты\" и я покажу, как это делать");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #6: beemoTutorialEnd

	void passage6_Init()
	{
		this.Passages[@"beemoTutorialEnd"] = new StoryPassage(@"beemoTutorialEnd", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Итак, ты готов и мы начинаем!");
		yield return lineBreak();
		yield return link("Начать", "storyStart", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #7: storyStart

	void passage7_Init()
	{
		this.Passages[@"storyStart"] = new StoryPassage(@"storyStart", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}