/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: GFDsecond.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @GFDsecond: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("firstOption", () => this.@firstOption, val => this.@firstOption = val);
			VarDef("secondOption", () => this.@secondOption, val => this.@secondOption = val);
			VarDef("thirdOption", () => this.@thirdOption, val => this.@thirdOption = val);
			VarDef("havePortableConcentrator", () => this.@havePortableConcentrator, val => this.@havePortableConcentrator = val);
			VarDef("hungry", () => this.@hungry, val => this.@hungry = val);
			VarDef("haveBeastFang", () => this.@haveBeastFang, val => this.@haveBeastFang = val);
			VarDef("workerName", () => this.@workerName, val => this.@workerName = val);
			VarDef("workerSign", () => this.@workerSign, val => this.@workerSign = val);
			VarDef("workerFriend", () => this.@workerFriend, val => this.@workerFriend = val);
			VarDef("banditName", () => this.@banditName, val => this.@banditName = val);
			VarDef("banditSign", () => this.@banditSign, val => this.@banditSign = val);
			VarDef("BanditSign", () => this.@BanditSign, val => this.@BanditSign = val);
			VarDef("haveNullSign", () => this.@haveNullSign, val => this.@haveNullSign = val);
			VarDef("banditFriend", () => this.@banditFriend, val => this.@banditFriend = val);
			VarDef("teamMemberCount", () => this.@teamMemberCount, val => this.@teamMemberCount = val);
		}

		public StoryVar @firstOption;
		public StoryVar @secondOption;
		public StoryVar @thirdOption;
		public StoryVar @havePortableConcentrator;
		public StoryVar @hungry;
		public StoryVar @haveBeastFang;
		public StoryVar @workerName;
		public StoryVar @workerSign;
		public StoryVar @workerFriend;
		public StoryVar @banditName;
		public StoryVar @banditSign;
		public StoryVar @BanditSign;
		public StoryVar @haveNullSign;
		public StoryVar @banditFriend;
		public StoryVar @teamMemberCount;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@GFDsecond()
	{
		this.StartPassage = "beemoIntroduce";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
		passage32_Init();
		passage33_Init();
		passage34_Init();
		passage35_Init();
		passage36_Init();
		passage37_Init();
		passage38_Init();
		passage39_Init();
		passage40_Init();
		passage41_Init();
		passage42_Init();
		passage43_Init();
		passage44_Init();
		passage45_Init();
		passage46_Init();
		passage47_Init();
		passage48_Init();
		passage49_Init();
		passage50_Init();
		passage51_Init();
		passage52_Init();
		passage53_Init();
		passage54_Init();
		passage55_Init();
		passage56_Init();
		passage57_Init();
		passage58_Init();
		passage59_Init();
		passage60_Init();
		passage61_Init();
		passage62_Init();
		passage63_Init();
		passage64_Init();
		passage65_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: beemoIntroduce

	void passage1_Init()
	{
		this.Passages[@"beemoIntroduce"] = new StoryPassage(@"beemoIntroduce", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\tПривет, путешественник! ");
		yield return lineBreak();
		yield return text("\tНадеюсь, для тебя уже стало очевидно, что ты заперт на этой поляне. Для того что" +
		    "бы выбраться, тебе придётся пройти мою игру. Сейчас расскажу, как мной пользоват" +
		    "ься.");
		yield return lineBreak();
		yield return link("Начать обучение", "beemoStartTutorial", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #2: beemoStartTutorial

	void passage2_Init()
	{
		this.Passages[@"beemoStartTutorial"] = new StoryPassage(@"beemoStartTutorial", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\tЯ расскажу тебе историю, но исход зависит только от тебя. Ты можешь делать выбор" +
		    ", нажимая на кнопки, которые появляются под экраном. Попробуй нажать на одну из " +
		    "трёх кнопок.");
		yield return lineBreak();
		yield return link("Попробовать", "beemoMoney", null);
		yield return text("\t");
		yield return lineBreak();
		yield return link("Попробовать", "beemoMoney", null);
		yield return lineBreak();
		yield return link("Открыть выход", "beemoHahaMoney", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #3: beemoMoney

	void passage3_Init()
	{
		this.Passages[@"beemoMoney"] = new StoryPassage(@"beemoMoney", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\tВ дальнейшем, чтобы сделать выбор, тебе необходимо будет платить монетами. Их ко" +
		    "личество отображается в верхней части моего экрана.");
		yield return lineBreak();
		yield return link("Понятно", "beemoGoToRunTutorial", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #4: beemoHahaMoney

	void passage4_Init()
	{
		this.Passages[@"beemoHahaMoney"] = new StoryPassage(@"beemoHahaMoney", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\tХа-ха-ха! ");
		yield return lineBreak();
		yield return text("\tТы и правда думал, что я так просто тебя отпущу? ");
		yield return lineBreak();
		yield return text("\tЗабудем про твою попытку побега и вернемся к обучению. ");
		yield return lineBreak();
		yield return text("\tВ дальнейшем, чтоб сделать выбор, тебе необходимо будет платить монетами. Их кол" +
		    "ичество отображается в верхней части моего экрана.");
		yield return lineBreak();
		yield return link("Понятно", "beemoGoToRunTutorial", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #5: beemoGoToRunTutorial

	void passage5_Init()
	{
		this.Passages[@"beemoGoToRunTutorial"] = new StoryPassage(@"beemoGoToRunTutorial", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\tЗаработать их ты сможешь, потратив самое дорогое, что у тебя есть!");
		yield return lineBreak();
		yield return text("\tНажимай на кнопку в виде монеты, и я покажу, как это делать.");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #6: beemoTutorialEnd

	void passage6_Init()
	{
		this.Passages[@"beemoTutorialEnd"] = new StoryPassage(@"beemoTutorialEnd", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\tИтак, ты готов и мы начинаем!");
		yield return lineBreak();
		yield return link("Начать", "Episod1", null);
		yield return text("\t");
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #7: Episod1

	void passage7_Init()
	{
		this.Passages[@"Episod1"] = new StoryPassage(@"Episod1", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\tДля нашей героини день начался ужасно. Вместо желанного сна до полудня, Алекс пр" +
		    "оснулась в восемь утра из-за шума за окном.");
		yield return lineBreak();
		yield return text("\t- Ненавижу этот новый район - подумала она на долю секунды.");
		yield return lineBreak();
		yield return text(@"	Когда Алекс немного пришла в себя после столь внезапного пробуждения, в голове опять появилась мысль, которая тревожила её уже несколько месяцев: ""Зачем я подписалась на этот школьный проект? Проводила бы лето, как другие ребята: гуляла, загорала, общалась... Ах! Было бы с кем пообщаться.");
		yield return lineBreak();
		yield return text("\tКак бы то ни было, пора вставать\".");
		yield return lineBreak();
		yield return link("Подойти к окну", "NoiseExplaining", null);
		yield return lineBreak();
		yield return link("Проверить стенд с проектом", "MorningExperimentCheck", null);
		yield return lineBreak();
		yield return link("Пойти умываться", "GoToBath", null);
		yield return lineBreak();
		Vars.firstOption = 100;
		yield return lineBreak();
		Vars.secondOption = 50;
		yield return lineBreak();
		Vars.thirdOption = 20;
		yield break;
	}


	// .............
	// #8: NoiseExplaining

	void passage8_Init()
	{
		this.Passages[@"NoiseExplaining"] = new StoryPassage(@"NoiseExplaining", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text(@"	Алекс подошла к окну и, как и ожидала, увидела стройку напротив своих окон. Возводили новый жилой дом. Несколько человек с помощью экзокостюмов-концентраторов ловко поднимали бетонные блоки и ставили их один на другой так, будто они весили не больше, чем пушинка.");
		yield return lineBreak();
		yield return text("\tВсе благодаря технологии концентраторов, позволяющей собирать природную энергию " +
		    "и использовать её почти в любых целях. В данном случае, например, для перемещени" +
		    "я тяжелых объектов.");
		yield return lineBreak();
		yield return text("\t- Обожаю высокие технологии - восхитилась Алекс.");
		yield return lineBreak();
		yield return text("\tОни с семьей переехали в новый район три месяца назад. Так как друзей у Алекс ещ" +
		    "ё не было, а родители почти все время проводили на работе, она нашла для себя ра" +
		    "звлечение в  прогулках по бурно развивающемуся району и наблюдением за строителя" +
		    "ми.");
		yield return lineBreak();
		yield return link("Проверить эксперимент", "MorningExperimentCheck", null);
		yield return lineBreak();
		yield return link("Пойти умываться", "GoToBath", null);
		yield return lineBreak();
		Vars.firstOption = 50;
		yield return lineBreak();
		Vars.secondOption = 20;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #9: MorningExperimentCheck

	void passage9_Init()
	{
		this.Passages[@"MorningExperimentCheck"] = new StoryPassage(@"MorningExperimentCheck", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\tКак и ожидалось, за ночь проект сам не сделался, что с унынием отметила Алекс.");
		yield return lineBreak();
		yield return text("\tГероиня окинула стенд взглядом: он остался в том же состоянии, в котором и был о" +
		    "ставлен вчера вечером.");
		yield return lineBreak();
		yield return text(@"	Сам стенд представляет собой сферическую колбу, к которой подключено множество разнообразных датчиков. Он предназначен для извлечения природной энергии из окружающего мира и концентрации её внутри колбы. Примерно таким способом люди смогли подчинить себе природную энергию давным давно.");
		yield return lineBreak();
		yield return link("Пойти умываться", "GoToBath", null);
		yield return lineBreak();
		Vars.firstOption = 20;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #10: GoToBath

	void passage10_Init()
	{
		this.Passages[@"GoToBath"] = new StoryPassage(@"GoToBath", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\tЗайдя в ванну героиня поняла, что забыла надеть свой портативный концентратор из" +
		    "-за столь спонтанного пробуждения.");
		yield return lineBreak();
		yield return text("\t- Ну вот! С утра всё наперекосяк - подумала Алекс. - Ладно умоюсь по старинке, в" +
		    "ручную.");
		yield return lineBreak();
		yield return link("Позавтракать", "TakeBreakfast", null);
		yield return lineBreak();
		yield return link("Одеть концентратор", "EquipConcentrator", null);
		yield return lineBreak();
		Vars.firstOption = 50;
		yield return lineBreak();
		Vars.secondOption = 100;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #11: TakeBreakfast

	void passage11_Init()
	{
		this.Passages[@"TakeBreakfast"] = new StoryPassage(@"TakeBreakfast", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("\tКогда наша героиня зашла на кухню, перед ней встал самый тяжёлый выбор в  жизни:" +
		    " \"Чего бы скушать на завтрак?\" ");
		yield return lineBreak();
		yield return text("\tВпрочем этот вопрос вставал перед ней каждое утро.");
		yield return lineBreak();
		yield return link("Съесть тост с чаем", "ToastWithTea", null);
		yield return lineBreak();
		yield return link("Приготовить шашлык", "BarbequeOnKitchen", null);
		yield return lineBreak();
		if(Vars.havePortableConcentrator==true) {
			yield return text(" ");
		yield return link("Съесть кашку яичко и йогурт", "FullBreakfast", null);
		}
		yield return lineBreak();
		Vars.firstOption = 50;
		yield return lineBreak();
		Vars.secondOption = 50;
		yield return lineBreak();
		Vars.thirdOption = 50;
		yield break;
	}


	// .............
	// #12: EquipConcentrator

	void passage12_Init()
	{
		this.Passages[@"EquipConcentrator"] = new StoryPassage(@"EquipConcentrator", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("\tАлекс вернулась в свою комнату и взяла со стола свой портативный концентратор. ");
		yield return lineBreak();
		yield return text(@"	В неактивированном состоянии портативный концентратор выглядит как обычный браслет. Как только пользователь одевает его, он трансформируется в изящную перчатку и позволяет манипулировать небольшими объемами природной энергии. Такого устройства хватает для выполнения повседневных задач.");
		yield return lineBreak();
		yield return link("Позавтракать", "TakeBreakfast", null);
		yield return lineBreak();
		Vars.firstOption = 20;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield return lineBreak();
		Vars.havePortableConcentrator = true;
		yield break;
	}


	// .............
	// #13: ToastWithTea

	void passage13_Init()
	{
		this.Passages[@"ToastWithTea"] = new StoryPassage(@"ToastWithTea", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("\tБутерброд с колбаской был очень вкусным и закончился очень быстро.");
		yield return lineBreak();
		yield return text("\t- Для затравка пойдёт - подумала Алекса - а через часик ещё перекушу.");
		yield return lineBreak();
		yield return text("\tТак сильно наша героиня не ошибалась со времён своей первой влюблённости...");
		yield return lineBreak();
		yield return link("Приступить к проекту", "GoToProject", null);
		yield return lineBreak();
		Vars.hungry = true;
		yield return lineBreak();
		Vars.firstOption = 75;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #14: FullBreakfast

	void passage14_Init()
	{
		this.Passages[@"FullBreakfast"] = new StoryPassage(@"FullBreakfast", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("\tЗакинув в рот последнюю ложку йогурта, Алекс откинулась на спинку дивана и подум" +
		    "ала:");
		yield return lineBreak();
		yield return text("\t- Сто лет не завтракала так плотно! Теперь смогу быть активной до самого вечера!" +
		    "");
		yield return lineBreak();
		yield return link("Приступить к проекту", "GoToProject", null);
		yield return lineBreak();
		Vars.hungry = false;
		yield return lineBreak();
		Vars.firstOption = 75;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #15: BarbequeOnKitchen

	void passage15_Init()
	{
		this.Passages[@"BarbequeOnKitchen"] = new StoryPassage(@"BarbequeOnKitchen", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("\tИдея жаренного на костре мяса так понравилась Алекс с утра, что она сразу присту" +
		    "пила к её воплощению. Разломала кухонные табуретки, затем подожгла их и стала жд" +
		    "ать. К сожалению, огонь не понял желаний главной героини и вскоре охватил весь д" +
		    "ом. ");
		yield return lineBreak();
		yield return text("\tАлекс погибла в адских муках.");
		yield return lineBreak();
		yield return link("Начать с начала", "Episod1", null);
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #16: GoToProject

	void passage16_Init()
	{
		this.Passages[@"GoToProject"] = new StoryPassage(@"GoToProject", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("\tКогда наша героиня пришла в комнату, где установлен стенд, на неё сразу навалило" +
		    "сь уныние. Она проводит этот эксперимент по наблюдению за концентрированной прир" +
		    "одной энергией уже в сорок второй раз и никаких новых результатов она не получал" +
		    "а уже давно.");
		yield return lineBreak();
		yield return text(@"	Сам эксперимент заключается в сборе природной энергии с помощью стенда, и наблюдении за её поведением, как визуально, так и с помощью датчиков. Сбор производится автоматически специальным энергонасосом. Далеко ходить не надо, так как природная энергия существует повсеместно, фактически вселенная состоит из неё.");
		yield return lineBreak();
		yield return text("\tА вот процесс наблюдения обычно весьма скучен, но в этом и суть системы образова" +
		    "ния - быть послушным терпилой.");
		yield return lineBreak();
		yield return link("Начать эксперимент", "ExperimentStart", null);
		yield return lineBreak();
		Vars.firstOption = 50;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #17: ExperimentStart

	void passage17_Init()
	{
		this.Passages[@"ExperimentStart"] = new StoryPassage(@"ExperimentStart", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("\tЭксперимент продолжался уже три часа...");
		yield return lineBreak();
		yield return text("\tОранжевый шарик энергии медленно вращался внутри корпуса стенда, но ничего необы" +
		    "чного не происходило.");
		yield return lineBreak();
		yield return text("\tУныние Алекс сменилось на раздражение, а потом и на злость.");
		yield return lineBreak();
		yield return text("\tАлекс захлестнуло чувство ненависти ко всему вокруг: к эксперименту, к себе и ко" +
		    " всему миру.");
		yield return lineBreak();
		yield return link("Попытаться ускорить процесс", "Forcing", null);
		yield return lineBreak();
		yield return link("Бросить всё", "Stopping", null);
		yield return lineBreak();
		Vars.firstOption = 150;
		yield return lineBreak();
		Vars.secondOption = 60;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #18: Forcing

	void passage18_Init()
	{
		this.Passages[@"Forcing"] = new StoryPassage(@"Forcing", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("\tАлекс раздраженно вскочила со стула и на глаза ей попался мобильный телефон. Мыс" +
		    "ль не заставила себя долго ждать и она тут же поместила его в колбу с природной " +
		    "энергией.");
		yield return lineBreak();
		yield return text("\tНеожиданно раздался громкий звук, похожий на щебет тысячи птиц, а за ним последо" +
		    "вал огромный по мощности взрыв, который стёр весь район, а вместе с ним и нашу г" +
		    "ероиню.");
		yield return lineBreak();
		yield return link("Начать с начала", "Episod1", null);
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #19: Stopping

	void passage19_Init()
	{
		this.Passages[@"Stopping"] = new StoryPassage(@"Stopping", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("\tАлекс вылетела из комнаты, плюнув на все меры предосторожности, связанные с эксп" +
		    "ериментом. Она совсем забыла о новом шкафу, который поставили её родители в кори" +
		    "доре, и стукнулась мизинцем об его угол.");
		yield return lineBreak();
		yield return text("\tВ этот момент её терпение лопнуло. Алекс начала проклинать всё на свете:");
		yield return lineBreak();
		yield return text("\t- Ненавижу эту новую квартиру!");
		yield return lineBreak();
		yield return text("\t- Ненавижу чёртову школу!");
		yield return lineBreak();
		yield return text("\t- Ненавижу чёртов эксперимент! Да зачем вообще мы подчинили эту энергию?");
		yield return lineBreak();
		yield return link("Далее", "Episode1End", null);
		yield return lineBreak();
		Vars.firstOption = 0;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #20: Episode1End

	void passage20_Init()
	{
		this.Passages[@"Episode1End"] = new StoryPassage(@"Episode1End", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("\tЧасто бывает в жизни, что мы задаём в пустоту миллион интересующий нас вопросов:" +
		    " \"Кто мы? Зачем мы родились? Когда всё это закончится?\" - и никогда не получаем " +
		    "на них ответов.");
		yield return lineBreak();
		yield return text("\tНо иногда вселенная обращает на это внимание и даёт нам ответы, но весьма изощре" +
		    "нными способами.");
		yield return lineBreak();
		yield return text("\tТак и случилось с нашей героиней. Природная энергия, сконцентрированная в экспер" +
		    "иментальном стенде вошла в резонанс с чрезвычайно сильными негативными эмоциями " +
		    "Алекс и отправила её туда, где она сможет получить свои ответы.");
		yield return lineBreak();
		yield return text("\tВнезапно квартира вокруг Алекс стала буквально растворяться в воздухе и вокруг н" +
		    "ачали вырисовываться деревья.");
		yield return lineBreak();
		yield return text("\tА через мгновение сознание покинуло Алекс...");
		yield return lineBreak();
		yield return text("\t");
		yield return link("Следующая глава", "Episode2", null);
		yield return lineBreak();
		Vars.firstOption = 500;
		yield return lineBreak();
		Vars.secondOption = 0;
		yield return lineBreak();
		Vars.thirdOption = 0;
		yield break;
	}


	// .............
	// #21: Episode2

	void passage21_Init()
	{
		this.Passages[@"Episode2"] = new StoryPassage(@"Episode2", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("\tКогда Алекс очнулась, солнце уже заходило. Девушка обнаружила себя посреди опушк" +
		    "и леса. Вокруг было очень тихо. Не было слышно ни стройки, ни машин. Только пени" +
		    "е птиц изредко разрушало эту тишину.");
		yield return lineBreak();
		yield return text("\t- Где это я очутилась? Я же была дома? Почему я упала в обморок? - миллион вопро" +
		    "сов крутилось в голове у Алекс.");
		yield return lineBreak();
		yield return text("\t- Давай будем рассуждать логично. Ближайщий лесопарк к моему дому находится в со" +
		    "седнем городе, я не могла там очутится.");
		yield return lineBreak();
		yield return text("\tНа краю поляны начиналась тропинка, которая привлекла внимание девушки.");
		yield return lineBreak();
		yield return link("Начать звать на помощь", "Scream", null);
		yield return lineBreak();
		yield return link("Пойти по тропинке", "WalkRoad", null);
		yield break;
	}


	// .............
	// #22: WalkRoad

	void passage22_Init()
	{
		this.Passages[@"WalkRoad"] = new StoryPassage(@"WalkRoad", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("\tТропинка была проложена через лесную чащу, и с каждой минутой Алекс всё сильней " +
		    "поражалась количеству деревьев. За всю свою жизнь она не видела их в таком колич" +
		    "естве.");
		yield return lineBreak();
		yield return text(@"	Внезапно впереди она услышала громкий нечеловеческий рык. Подкравшись немного поближе, она увидела как на поляне дерутся два диких зверя. Один был черный и невероятно мускулистый, отдаленно напоминающий пантеру, а второй имел массивное тело на коротких, но очень широких ногах, и острые рога.");
		yield return lineBreak();
		yield return link("Посмотреть битву", "WatchBattle", null);
		yield return lineBreak();
		yield return link("Пойти дальше", "GoFar", null);
		yield break;
	}


	// .............
	// #23: Scream

	void passage23_Init()
	{
		this.Passages[@"Scream"] = new StoryPassage(@"Scream", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("\tАлекс несколько раз громко позвала на помощь, и стала ждать.");
		yield return lineBreak();
		yield return text("\tЧерез минуту в кустах раздался шорох, и на поляну выскачило большое животное.");
		yield return lineBreak();
		yield return text("\tОно было похоже на пантеру, шкура черного цвета и невероятно мощная мускулатура." +
		    " Животное оскалило свои огромные клыки и с неожиданной грацией начало двигаться " +
		    "вокруг Алекс.");
		yield return lineBreak();
		yield return link("Прикинуться мёртвым", "BeLikeDead", null);
		yield return lineBreak();
		yield return link("Накричать на него", "ScreamToAnimal", null);
		yield return lineBreak();
		yield return link("Залезть на дерево", "ClimbToTree", null);
		yield break;
	}


	// .............
	// #24: BeLikeDead

	void passage24_Init()
	{
		this.Passages[@"BeLikeDead"] = new StoryPassage(@"BeLikeDead", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("\tАлекс упала навзнич, и постаралась не дышать. Это действие у неё получилось сове" +
		    "ршенно автоматически, она и сама не ожидала от себя такой реакции. ");
		yield return lineBreak();
		yield return text("\tЗверь подошёл поближе к девушке и начал обнюхивать её, а затем очень уютно замур" +
		    "чал и дважды лизнул Алекс по лицу.");
		yield return lineBreak();
		yield return text("\tВнезапно из чащи раздался нечеловечкий рёв, и большая киска побежала искать исто" +
		    "чник звука.");
		yield return lineBreak();
		yield return link("Пойти по тропинке", "GoFar", null);
		yield break;
	}


	// .............
	// #25: ScreamToAnimal

	void passage25_Init()
	{
		this.Passages[@"ScreamToAnimal"] = new StoryPassage(@"ScreamToAnimal", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("\tНабрав побольше воздуха в легкие Алекс, громко и продолжительно начала кричать в" +
		    " сторону животного.");
		yield return lineBreak();
		yield return text("\tСначала дикий зверь пришёл в смятение от происходящего, а после и совсем испугал" +
		    "ся неадекватности девушки и, поджав хвост, скрылся за деревьями.");
		yield return lineBreak();
		yield return link("Пойти по тропинке", "GoFar", null);
		yield break;
	}


	// .............
	// #26: ClimbToTree

	void passage26_Init()
	{
		this.Passages[@"ClimbToTree"] = new StoryPassage(@"ClimbToTree", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("\tАлекс забирается на ближайшее дерево так высоко, как только может. Оказавшись на" +
		    "верху девушка почувствовала себя в безопасности и начала продумывать план, как с" +
		    "пускаться.");
		yield return lineBreak();
		yield return text("\tК несчастью для Алекс, животное взяв небольшой разгон с легкостью добирается до " +
		    "неё. При падении Алекс ломает свою шею.");
		yield return lineBreak();
		yield return link("Начать с начала главы", "Episode2", null);
		yield break;
	}


	// .............
	// #27: WatchBattle

	void passage27_Init()
	{
		this.Passages[@"WatchBattle"] = new StoryPassage(@"WatchBattle", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text(@"	Бой длился недолго. Как бы ""пантера"" не пыталась нанести урон своему сопернику, у неё не получалось пробить толстенную шкуру, но стоило её ошибится один раз, и она тут же напоролась на острый рог животом, и упала на землю уже мёртвой. Её опонент не проявил интересе к трупу, и молча, с гордостью победителя, убежал в лес.");
		yield return lineBreak();
		yield return text("\t\tАлекс подождала ещё несколько минут в укрытии, а потом решилась подойти к трупу" +
		    ". Её очень привлекли острые клыки дикого зверя и она оторвала себе один из них н" +
		    "а память.");
		yield return lineBreak();
		yield return link("Пойти дальше", "GoFar", null);
		yield return lineBreak();
		Vars.haveBeastFang = true;
		yield break;
	}


	// .............
	// #28: GoFar

	void passage28_Init()
	{
		this.Passages[@"GoFar"] = new StoryPassage(@"GoFar", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("\tЧерез пятнадцать минут путешествия по лесу, Алекс наконец выбралась из него и ув" +
		    "идела перед собой деревянные дома. Их было много, целая деревня, а в далеке на х" +
		    "олме виднелся замок. Около ближайшего дома на огороде работал человек.");
		yield return lineBreak();
		yield return text("\t- Эти дома из дерева? - спросила себя Алекс. - Никогда в жизни не видела такого." +
		    " И почему этот человек так странно одет. Какая нелепая шляпа и порванные штаны с" +
		    " рубахой.");
		yield return lineBreak();
		yield return link("Подойти к парню", "TalkToWorker", null);
		yield return lineBreak();
		yield return link("Пойти вглубь деревни", "GoToVillageCenter", null);
		yield return lineBreak();
		yield return link("Зайти в крайнюю хату", "GoInsideHouse", null);
		yield break;
	}


	// .............
	// #29: TalkToWorker

	void passage29_Init()
	{
		this.Passages[@"TalkToWorker"] = new StoryPassage(@"TalkToWorker", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text("\tПодойдя к человеку поближе, девушка смогла разглядеть его получше. Он был средне" +
		    "го роста и носил длинные волосы. На вид ему было лет двадцать. ");
		yield return lineBreak();
		yield return text("\tАлекс сразу подумала, что в других обстаятельствах, с удоаовльствием бы утонула " +
		    "в его зелёных глазах.");
		yield return lineBreak();
		yield return text("\tКогда Алекс опустила глаза, её взгляд привлекла странная татуировка на его левой" +
		    " руке.");
		yield return lineBreak();
		yield return text("\t- Приветк! Ты выглядишь расстерянной, что с тобой случилось? - начал разговор мо" +
		    "лодой человек.");
		yield return lineBreak();
		yield return link("Что это за место?", "WorkerVillage", null);
		yield return lineBreak();
		yield return link("Интересная татуировка", "WorkerSign", null);
		yield return lineBreak();
		yield return link("Как тебя зовут?", "WorkerName", null);
		yield break;
	}


	// .............
	// #30: GoToVillageCenter

	void passage30_Init()
	{
		this.Passages[@"GoToVillageCenter"] = new StoryPassage(@"GoToVillageCenter", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return text("\tПройдя вглубь деревни, Алекс вышла на небольшую площадь и сразу приметила тракти" +
		    "р на противоположной стороне. Направившись решительным шагов в сторону трактира," +
		    " девушка не заметила идущего перпендикулярно ей человека и они столкнулись.");
		yield return lineBreak();
		yield return text("\tАлекс хотела извиниться, но взглянув в его лицо немного замялась. Выражение этог" +
		    "о лица явно не сулило ничего хорошего.");
		yield return lineBreak();
		yield return text("\t- Смотри куда прёшь, букашка мелкая! - взревел прохожий.");
		yield return lineBreak();
		yield return link("Выебнуться на него", "BeBrave", null);
		yield return lineBreak();
		yield return link("Промолчать", "BeCoward", null);
		yield break;
	}


	// .............
	// #31: GoInsideHouse

	void passage31_Init()
	{
		this.Passages[@"GoInsideHouse"] = new StoryPassage(@"GoInsideHouse", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		yield return text("\tВнутри дома стояла большая белая печь. В ней весело горел огонь, и готовилось чт" +
		    "о-то невероятно ароматное. В целом внутреннее убранство было весьма скромным: де" +
		    "ревянные стол и лавки, а в углу расположился небольшой алтарь. Алекс никогда так" +
		    "их не видела.");
		yield return lineBreak();
		yield return text("\t- Дочька, присаживайся, да расскажи, что с тобой приключилось. Вид у тебя больно" +
		    " напуганный.");
		yield return lineBreak();
		yield return text("\tАлекс рассказала всё, что с ней произошло за последнее время, всё, что она могла" +
		    " хоть как-то описать и объяснить, начиная с самого утра этого дня, когда она про" +
		    "снулась у себя в кровати.");
		yield return lineBreak();
		yield return link("Далее", "AskWhatsNext", null);
		yield return lineBreak();
		if(Vars.workerName==true&& Vars.workerSign==true) {
			yield return text(" ");
			Vars.workerFriend = true;
		}
		yield return lineBreak();
		if(Vars.banditName==true&& Vars.banditSign==true) {
			yield return text(" ");
			Vars.workerFriend = true;
		}
		yield break;
	}


	// .............
	// #32: WorkerSign

	void passage32_Init()
	{
		this.Passages[@"WorkerSign"] = new StoryPassage(@"WorkerSign", new string[]{  }, passage32_Main);
	}

	IStoryThread passage32_Main()
	{
		yield return text("\t- Это не татуировка, а метка Нулла. Такие есть у всех нуллов, живущих в этой дер" +
		    "евне, их ставят при рождении. Они служат для того, что бы донумам было проще кон" +
		    "тролировать население и удерживать нас на местах.");
		yield return lineBreak();
		yield return link("Как тебя зовут?", "WorkerName", null);
		yield return lineBreak();
		yield return link("Что это за место?", "WorkerVillage", null);
		yield return lineBreak();
		yield return link("Пойти в хату", "GoInsideHouse", null);
		yield return lineBreak();
		Vars.workerSign = true;
		yield break;
	}


	// .............
	// #33: WorkerVillage

	void passage33_Init()
	{
		this.Passages[@"WorkerVillage"] = new StoryPassage(@"WorkerVillage", new string[]{  }, passage33_Main);
	}

	IStoryThread passage33_Main()
	{
		yield return text("\t- Эта деревня называется Инитиум, самое крайнее поселение Алиоса.");
		yield return lineBreak();
		yield return text("\t\"Ага, хорошо, что я нахожусь хотя бы в своём мире, но вот деревень не существует" +
		    " уже много сотен лет\".");
		yield return lineBreak();
		yield return link("Какой сейчас год", "WorkerYear", null);
		yield break;
	}


	// .............
	// #34: WorkerName

	void passage34_Init()
	{
		this.Passages[@"WorkerName"] = new StoryPassage(@"WorkerName", new string[]{  }, passage34_Main);
	}

	IStoryThread passage34_Main()
	{
		yield return text("\t- Не думая, что мы знакомы. Меня зовут Алекс, а тебя? - спросила Алекс без тени " +
		    "смущения.");
		yield return lineBreak();
		yield return text("\t- А меня зовут Фёдор, но для друзей просто Федя - парень скромно улыбнулся в отв" +
		    "ет.");
		yield return lineBreak();
		yield return link("Интересная татуировка", "WorkerSign", null);
		yield return lineBreak();
		yield return link("Что это за место?", "WorkerVillage", null);
		yield return lineBreak();
		yield return link("Пойти в хату", "GoInsideHouse", null);
		yield return lineBreak();
		Vars.workerName = true;
		yield break;
	}


	// .............
	// #35: BeBrave

	void passage35_Init()
	{
		this.Passages[@"BeBrave"] = new StoryPassage(@"BeBrave", new string[]{  }, passage35_Main);
	}

	IStoryThread passage35_Main()
	{
		yield return text("\tАлекс совсем не напряглась от такого своеобразного приветствия и ответила спокой" +
		    "ным голосом:");
		yield return lineBreak();
		yield return text("\t- Эй, великан, эта улица не только твоя, так что будь поскромней.");
		yield return lineBreak();
		yield return text("\tМужчина сначала пришёл в замешательство, он явно не ожидал такого ответа, а пото" +
		    "м расплылся в теплой улыбке:");
		yield return lineBreak();
		yield return text("\t- Меня зовут Роджер. А как тебя зовут? Я раньше тебя не видел.");
		yield return lineBreak();
		yield return text("\t- Меня зовут Алекс и я потерялась. - Девушка наконец смогла окинуть взором своег" +
		    "о собедесдника. На виде ему было лет 50, но он был черезвычайно активен для свои" +
		    "х лет. На левой руке у него была странная татуировка.");
		yield return lineBreak();
		yield return link("Интересная татуировка", "BanditSign", null);
		yield return lineBreak();
		yield return link("Что это за место", "BanditVillage", null);
		yield break;
	}


	// .............
	// #36: BeCoward

	void passage36_Init()
	{
		this.Passages[@"BeCoward"] = new StoryPassage(@"BeCoward", new string[]{  }, passage36_Main);
	}

	IStoryThread passage36_Main()
	{
		yield return text("\tАлекс только хотела продолжить движение в сторону трактира, как ей прилетела опл" +
		    "еуха и она в миг очутилась на земле.");
		yield return lineBreak();
		yield return text("\t- Смотри впредь по сторонам, букашка! - грозно сказал мужчина.");
		yield return lineBreak();
		yield return link("Лежать на земле", "KeepLying", null);
		yield return lineBreak();
		if(Vars.havePortableConcentrator==true) {
			yield return text(" ");
		yield return link("Использовать концентратор", "BanditSmash", null);
		}
		yield break;
	}


	// .............
	// #37: BanditSign

	void passage37_Init()
	{
		this.Passages[@"BanditSign"] = new StoryPassage(@"BanditSign", new string[]{  }, passage37_Main);
	}

	IStoryThread passage37_Main()
	{
		yield return text("\t- Аааа, ты про этот значок? Эти проклятые донумы клеймят ими нас, нуллов, при ро" +
		    "ждении, как скот. Им так видите ли, легче нас контролировать... Ублюдки! И в ито" +
		    "ге с этим значком я могу находится только в этой деревне.");
		yield return lineBreak();
		yield return link("Что это за место", "BanditVillage", null);
		yield return lineBreak();
		yield return link("Пойти в хату", "GoInsideHouse", null);
		yield return lineBreak();
		Vars.BanditSign = true;
		yield break;
	}


	// .............
	// #38: BanditYear

	void passage38_Init()
	{
		this.Passages[@"BanditYear"] = new StoryPassage(@"BanditYear", new string[]{  }, passage38_Main);
	}

	IStoryThread passage38_Main()
	{
		yield return text("\t- Сейчас 542 год от Великого Переселения.");
		yield return lineBreak();
		yield return link("Невозможно!!!", "YearWonderBandit", null);
		yield break;
	}


	// .............
	// #39: KeepLying

	void passage39_Init()
	{
		this.Passages[@"KeepLying"] = new StoryPassage(@"KeepLying", new string[]{  }, passage39_Main);
	}

	IStoryThread passage39_Main()
	{
		yield return text("\tПротивный мужик пошёл своей дорогой, а Алекс осталась лежать на земле. Она устав" +
		    "илась в небо, по которому медленно проплывали беспечные облака. Внезапное чувств" +
		    "о тоски накатило на нашу героиню, и слёзы чуть было не брызнули из глаз.");
		yield return lineBreak();
		yield return text("\t- Доченька, ты чего лежишь на землице холодной, - произнес добрый и нежный голос" +
		    ".");
		yield return lineBreak();
		yield return text("\tАлекс подняла взгляд и увидела, что с ней разговаривает милая старушка.");
		yield return lineBreak();
		yield return text("\t- Вставай, пойдём ко мне в дом!");
		yield return lineBreak();
		yield return link("Пойти со старушкой", "GoInsideHouse", null);
		yield break;
	}


	// .............
	// #40: BanditSmash

	void passage40_Init()
	{
		this.Passages[@"BanditSmash"] = new StoryPassage(@"BanditSmash", new string[]{  }, passage40_Main);
	}

	IStoryThread passage40_Main()
	{
		yield return text("\tВнезапно ярость захлестнула Алекс, увеличилась концентрация адреналина в крови и" +
		    " сердце начало бешено стучаться.");
		yield return lineBreak();
		yield return text("\tДевушка встала на ноги, подняла обидчика с помощью портативного концентратора в " +
		    "воздух и с размаху швырнула его об стену дома. Тот моментально потерял сознание." +
		    " ");
		yield return lineBreak();
		yield return text("\tНемного придя в себя, Алекс поняла что вокруг неё уже столпилось много народа. ");
		yield return lineBreak();
		yield return text("\tТут из толпы выбежали два человека в легких доспехах. Один из них пару раз взмах" +
		    "нул руками и Алекс внезапно упала на землю, а руки сами свелись за спиной. Второ" +
		    "й подбежал и снял с руки девушки концентратор.");
		yield return lineBreak();
		yield return text("\t- Смотри, у неё нет знака! - крикнул один стражник другому.");
		yield return lineBreak();
		yield return link("Вы не имеете права!", "TalkWithGuards", null);
		yield return lineBreak();
		Vars.havePortableConcentrator = false;
		yield break;
	}


	// .............
	// #41: TalkWithGuards

	void passage41_Init()
	{
		this.Passages[@"TalkWithGuards"] = new StoryPassage(@"TalkWithGuards", new string[]{  }, passage41_Main);
	}

	IStoryThread passage41_Main()
	{
		yield return text("\t- В тюрьме будешь возмущаться! - ответил на её вопль стражник.");
		yield return lineBreak();
		yield return text("\tПотом Алекс увидела, как он взмахнул руками, а потом она вырубилась");
		yield return lineBreak();
		yield return link("Дальше", "WakeUpInJail", null);
		yield break;
	}


	// .............
	// #42: AskWhatsNext

	void passage42_Init()
	{
		this.Passages[@"AskWhatsNext"] = new StoryPassage(@"AskWhatsNext", new string[]{  }, passage42_Main);
	}

	IStoryThread passage42_Main()
	{
		yield return text("\tКогда Алекс закончила свой рассказ, на улице уже стемнело.");
		yield return lineBreak();
		yield return text(@"	- 2542-ой год, огромные каменные дома, высокие технологии, доступные каждому - всё это кажется мне фантастическим - сказала старушка. - Сейчас 542-ой год от Великого Переселения, мы возделываем поля, выращиваем скот и опасаемся диких животных. Похоже, что каким-то образом ты перенеслась в прошлое! Тут тебе понадобится помощь мудрейших из донумов.");
		yield return lineBreak();
		yield return text("\t- Я даже не знаю, где они находятся, но возможно верховный донум нашей деревни, " +
		    "его ещё называют иерарх, сможет подсказать тебе.");
		yield return lineBreak();
		yield return text("\t- Но добраться до него, не так-то просто. Он живёт в Небесном районе деревни, та" +
		    "м где живут только донумы. Вход туда разрешён только жителям и нуллам, отмеченны" +
		    "м знаком деревни. А у тебя, как раз нет знака. Стража не пропустит тебя.");
		yield return lineBreak();
		yield return text("\t- Но я знаю, как помочь тебе!");
		yield return lineBreak();
		yield return link("Спросить про донумов", "AskAboutDonum", null);
		yield return lineBreak();
		yield return link("Пойти в верхний город", "GoToUpperTown", null);
		yield return lineBreak();
		yield return link("Спросить про знак", "GrandMaSignQuestIntroduce", null);
		yield break;
	}


	// .............
	// #43: GoToUpperTown

	void passage43_Init()
	{
		this.Passages[@"GoToUpperTown"] = new StoryPassage(@"GoToUpperTown", new string[]{  }, passage43_Main);
	}

	IStoryThread passage43_Main()
	{
		yield return text("\tАлекс решила проигнорировать все предостережения доброжелательной старушки и отп" +
		    "равилась к воротам Небесного района.");
		yield return lineBreak();
		yield return text("\tВход охранялся двумя стражниками. Они были одеты в легкие кожанные доспехи, и на" +
		    " вид был совсем не опасными, но интуиция подсказывала, что с ними лучше не шутит" +
		    "ь.");
		yield return lineBreak();
		yield return link("Вернуться к старушке", "AskWhatsNext", null);
		yield return lineBreak();
		yield return link("Направиться ко входу", "GoToEntrance", null);
		yield break;
	}


	// .............
	// #44: GrandMaSignQuestIntroduce

	void passage44_Init()
	{
		this.Passages[@"GrandMaSignQuestIntroduce"] = new StoryPassage(@"GrandMaSignQuestIntroduce", new string[]{  }, passage44_Main);
	}

	IStoryThread passage44_Main()
	{
		yield return text("\t- Эти знаки ставятся при рождении с помощью магии. Таким образом, мы, нуллы, ока" +
		    "зываемся привязанными к одной территории.");
		yield return lineBreak();
		yield return text("\t- Есть у нас в деревне один человек, который сможет помочь тебе с этим, но он не" +
		    " очень общительный, и уж точно никому не доверяет. Он живёт недалеко, отправляйс" +
		    "я к нему сейчас же.");
		yield return lineBreak();
		yield return link("Пойти", "GoToDarkDonum", null);
		yield break;
	}


	// .............
	// #45: GoToEntrance

	void passage45_Init()
	{
		this.Passages[@"GoToEntrance"] = new StoryPassage(@"GoToEntrance", new string[]{  }, passage45_Main);
	}

	IStoryThread passage45_Main()
	{
		yield return text("Алекс подходит к стражникам");
		yield return lineBreak();
		yield return text("Описание стражников");
		yield return lineBreak();
		yield return link("Пройти мимо них", "WalkPastGuards", null);
		yield return lineBreak();
		if(Vars.haveNullSign==true) {
			yield return text(" ");
		yield return link("Показать знак", " ShowSignByAlex", null);
		}
		yield break;
	}


	// .............
	// #46: WalkPastGuards

	void passage46_Init()
	{
		this.Passages[@"WalkPastGuards"] = new StoryPassage(@"WalkPastGuards", new string[]{  }, passage46_Main);
	}

	IStoryThread passage46_Main()
	{
		yield return text("Стражники останавливают Алекс и требуют показать знак нулла");
		yield return lineBreak();
		yield return link("Показать фак", "ShowFuck", null);
		yield return lineBreak();
		if(Vars.haveNullSign==true) {
			yield return text(" ");
		yield return link("Показать знак", " ShowSignByGuard", null);
		}
		yield break;
	}


	// .............
	// #47:  ShowSignByAlex

	void passage47_Init()
	{
		this.Passages[@" ShowSignByAlex"] = new StoryPassage(@" ShowSignByAlex", new string[]{  }, passage47_Main);
	}

	IStoryThread passage47_Main()
	{
		yield return text("Стражники проверяют знак");
		yield return lineBreak();
		yield return text("Алекс напрягается");
		yield return lineBreak();
		yield return text("Стражники пропускают её дальше");
		yield break;
	}


	// .............
	// #48: ShowFuck

	void passage48_Init()
	{
		this.Passages[@"ShowFuck"] = new StoryPassage(@"ShowFuck", new string[]{  }, passage48_Main);
	}

	IStoryThread passage48_Main()
	{
		yield return text("Стражники кастуют свою крутую магию и вырубают Алекс");
		yield return lineBreak();
		yield return text("Очнётся она уже в тюрьме");
		yield return lineBreak();
		yield return link("Дальше", "WakeUpInJail", null);
		yield break;
	}


	// .............
	// #49:  ShowSignByGuard

	void passage49_Init()
	{
		this.Passages[@" ShowSignByGuard"] = new StoryPassage(@" ShowSignByGuard", new string[]{  }, passage49_Main);
	}

	IStoryThread passage49_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #50: WakeUpInJail

	void passage50_Init()
	{
		this.Passages[@"WakeUpInJail"] = new StoryPassage(@"WakeUpInJail", new string[]{  }, passage50_Main);
	}

	IStoryThread passage50_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #51: YearWonder

	void passage51_Init()
	{
		this.Passages[@"YearWonder"] = new StoryPassage(@"YearWonder", new string[]{  }, passage51_Main);
	}

	IStoryThread passage51_Main()
	{
		yield return text("\tАлекс впала в ступор, в её голове закружился целый торнадо из мыслей.");
		yield return lineBreak();
		yield return text("\t\"Как это возможно? Как я переместилась на две тысячи в прошлое? Так не бывает\".");
		yield return lineBreak();
		yield return text("\tНесколько минут понадобилось Алекс, чтобы перевести дух.");
		yield return lineBreak();
		yield return link("Как тебя зовут?", "WorkerName", null);
		yield return lineBreak();
		yield return link("Что это за метка?", "WorkerSign", null);
		yield return lineBreak();
		yield return link("Пойти в хату", "GoInsideHouse", null);
		yield break;
	}


	// .............
	// #52: YearWonderBandit

	void passage52_Init()
	{
		this.Passages[@"YearWonderBandit"] = new StoryPassage(@"YearWonderBandit", new string[]{  }, passage52_Main);
	}

	IStoryThread passage52_Main()
	{
		yield return text("\tАлекс впала в ступор, в её голове закружился целый торнадо из мыслей.");
		yield return lineBreak();
		yield return text("\t\"Как это возможно? Как я переместилась на две тысячи в прошлое? Так не бывает\".");
		yield return lineBreak();
		yield return text("\tНесколько минут понадобилось Алекс, чтобы перевести дух.");
		yield return lineBreak();
		yield return link("Интересная татуировка", "BanditSign", null);
		yield return lineBreak();
		yield return link("Пойти в хату", "GoInsideHouse", null);
		yield break;
	}


	// .............
	// #53: AskAboutDonum

	void passage53_Init()
	{
		this.Passages[@"AskAboutDonum"] = new StoryPassage(@"AskAboutDonum", new string[]{  }, passage53_Main);
	}

	IStoryThread passage53_Main()
	{
		yield return text(@"	Человечество поделено на две касты: донумы - люди, которые обладают врожденными способностями к магии - и нуллы - все остальные, кто не обладает никакими сверхспособностями. Нуллы способны собирать и концентрировать природную энергию, из которой, по сути, состоит мир, и использовать её по своему усмотрению. Могут созидать, а могут и разрушать, могут делать, всё, на что хватит фантазии. Такие способности проявляются примерно у половины людей.");
		yield return lineBreak();
		yield return text("\tНа фоне явного преимущества в силе донумы уже давно захватили власть во всём мир" +
		    "е. Но не смотря на то, что мы, нуллы, живём бедно и работаем на них, они нас не " +
		    "сильно тревожат.");
		yield return lineBreak();
		yield return link("Пойти в верхний город", "GoToUpperTown", null);
		yield return lineBreak();
		yield return link("Спросить про знак", "GrandMaSignQuestIntroduce", null);
		yield break;
	}


	// .............
	// #54: GoToDarkDonum

	void passage54_Init()
	{
		this.Passages[@"GoToDarkDonum"] = new StoryPassage(@"GoToDarkDonum", new string[]{  }, passage54_Main);
	}

	IStoryThread passage54_Main()
	{
		yield return text("\tАлекс подошла к необходимому дому и постучала в дверь. Никто не ответил, но двер" +
		    "ь приоткрылась и девушка решила зайти.");
		yield return lineBreak();
		yield return text(@"	Внутри дом освещался несколькими свечами, но этого было достаточно, чтобы разглядеть странный дизайн внутреннего убранства. Все стены, пол и потолок были изрисованы какими-то непонятными символами. Сделав пару шагов внутрь, Алекс услышала голос, исходивший из темного угла:");
		yield return lineBreak();
		yield return text("\t- Кто ты и что тебе здесь надо?");
		yield return lineBreak();
		yield return link("Мне нужна помощь со знаком", "CanYouMakeSign", null);
		yield return lineBreak();
		yield return link("Как тебя зовут", "AskDarkDonumName", null);
		yield break;
	}


	// .............
	// #55: CanYouMakeSign

	void passage55_Init()
	{
		this.Passages[@"CanYouMakeSign"] = new StoryPassage(@"CanYouMakeSign", new string[]{  }, passage55_Main);
	}

	IStoryThread passage55_Main()
	{
		yield return text("\tАлекс рассказала свою необычную историю.");
		yield return lineBreak();
		yield return text("\t- А теперь мне нужно пробраться в Небесный район, чтобы спросить совета у иерарх" +
		    "а. Но для этого мне нужно получить знак нулла - закончила свою историю девушка.");
		yield return lineBreak();
		yield return text(@"	- Ты рассказываешь удивительные вещи, девочка, и я тебя верю - ответил человек из темноты - Я помогу тебе со знаком, но сначала окажи и ты мне услугу. Человек по имени Роджер обещал мне принести клык хищной кошки, деньги получил, а работу не сделал. Разберись с этим.");
		yield return lineBreak();
		yield return link("Пойти к Роджеру", "GoToBanditHouse", null);
		yield return lineBreak();
		if(Vars.haveBeastFang==true) {
			yield return text(" ");
		yield return link("У меня есть клык", "ComeBack", null);
		}
		yield return lineBreak();
		if(Vars.workerFriend==true) {
			yield return text(" ");
		yield return link("Попросить поомощи у Феди", "TakeWorkerHelp", null);
		}
		yield break;
	}


	// .............
	// #56: AskDarkDonumName

	void passage56_Init()
	{
		this.Passages[@"AskDarkDonumName"] = new StoryPassage(@"AskDarkDonumName", new string[]{  }, passage56_Main);
	}

	IStoryThread passage56_Main()
	{
		yield return text("\t- Девочка, ты вломилась ко мне в дом, не отвечаешь на мои вопросы, а в ответ зад" +
		    "аешь свои! - сказал голос из темноты. - Тебе не кажется, что мы не так близко зн" +
		    "акомы?");
		yield return lineBreak();
		yield return text("\t- Итак, повторю свой вопрос. Кто ты и что ты здесь забыла?");
		yield return lineBreak();
		yield return link("Мне нужна помощь со знаком", "CanYouMakeSign", null);
		yield return lineBreak();
		yield return link("Символы на стенах", "AskAboutDarkDonumHouse", null);
		yield break;
	}


	// .............
	// #57: AskAboutDarkDonumHouse

	void passage57_Init()
	{
		this.Passages[@"AskAboutDarkDonumHouse"] = new StoryPassage(@"AskAboutDarkDonumHouse", new string[]{  }, passage57_Main);
	}

	IStoryThread passage57_Main()
	{
		yield return text("\t- Ты мне надоела, глупая девчонка! Иди вон отсюда!");
		yield return lineBreak();
		yield return text("\tСама того неожидая, Алекс послушно выходит из дома. Дверь за ней захлопнулась и " +
		    "больше не поддавалась.");
		yield return lineBreak();
		yield return text("\tЕдинственное, что оставалось девушке, это отправиться к воротам, ведущим в Небес" +
		    "ный район");
		yield return lineBreak();
		yield return link("Направиться ко входу", "GoToEntrance", null);
		yield break;
	}


	// .............
	// #58: GoToBanditHouse

	void passage58_Init()
	{
		this.Passages[@"GoToBanditHouse"] = new StoryPassage(@"GoToBanditHouse", new string[]{  }, passage58_Main);
	}

	IStoryThread passage58_Main()
	{
		yield return text("\tАлекс после нескольких кругом по деревне нашла необходимый дом. Поднявшись на кр" +
		    "ыльцо, она постучала в дверь. ");
		yield return lineBreak();
		yield return text("\tДверь открыл уже немолодой человек с сонным лицом. ");
		yield return lineBreak();
		if(Vars.banditFriend==true) {
			yield return text("\tЭто был Роджер, мужчина с которым девушка столкнулась сегодня на площади.");
			yield return lineBreak();
			yield return text("\t- Алекс, что тебя привело ко мне среди ночи?");
		}
		yield return lineBreak();
		if(Vars.banditFriend==true) {
			yield return text(" ");
		yield return link("Попросить клык", "AskForPlant", null);
		}
		yield return lineBreak();
		if(Vars.teamMemberCount>1) {
			yield return text(" ");
		yield return link("Припугнуть", "AttackBandit", null);
		}
		yield return lineBreak();
		if(Vars.banditFriend==false&&Vars.teamMemberCount<2) {
			yield return text("\tОн оказался совсем не рад столько позднему визиту, схватил Алекс за шкирку и вык" +
		    "инул её прочь с крыльца.");
			yield return lineBreak();
			yield return text("\t- Не смей появляться больше ком не на глаза! ");
			yield return lineBreak();
			yield return text("\tНенадолго Алекс потеряла сознание");
		}
		yield return lineBreak();
		if(Vars.banditFriend==false&&Vars.teamMemberCount<2) {
			yield return text(" ");
		yield return link("Далее", "WakeUpAfterFail", null);
		}
		yield break;
	}


	// .............
	// #59: TakeWorkerHelp

	void passage59_Init()
	{
		this.Passages[@"TakeWorkerHelp"] = new StoryPassage(@"TakeWorkerHelp", new string[]{  }, passage59_Main);
	}

	IStoryThread passage59_Main()
	{
		yield return text("\t\"Дело, есть дело\" - подумала Алекс, и отправилась к дому Фёдора среди ночи. Стук" +
		    " в его дверь, конечно же разбудил его, но через тридцать секунд он открыл дверь." +
		    "");
		yield return lineBreak();
		yield return text("\t- Алекс!!! Это ты? Что случилось? - спросил Фёдор.");
		yield return lineBreak();
		yield return text("\t- Мне нужна твоя помощь, срочно! Одевайся и пойдём со мной!");
		yield return lineBreak();
		yield return text("\tТакому боевому настрою молодой парень не смог противостоять, и вскоре уже был го" +
		    "тов. ");
		yield return lineBreak();
		yield return link("Пойти к Роджеру", "GoToBanditHouse", null);
		yield return lineBreak();
		Vars.teamMemberCount = 2;
		yield break;
	}


	// .............
	// #60: AttackBandit

	void passage60_Init()
	{
		this.Passages[@"AttackBandit"] = new StoryPassage(@"AttackBandit", new string[]{  }, passage60_Main);
	}

	IStoryThread passage60_Main()
	{
		yield return text("\t- А ну-ка отдавай клык, за который ты уже получил плату, а не то мы с моим прият" +
		    "елем тебя так отделаем, что неделю лежать будешь! - Алекс неожидала от себя тако" +
		    "й прыти, но слова сами вылетали из её рта.");
		yield return lineBreak();
		yield return text("\tХозяин дома немного напрягся, затем скрылся в глубине дома.");
		yield return lineBreak();
		yield return text("\tЧерез несколько секунд он вернулся, отдал клык и захлопнул дверь, не сказав при " +
		    "этом ни слова.");
		yield return lineBreak();
		yield return link("Вернуться к донуму", "ComeBack", null);
		yield return lineBreak();
		Vars.teamMemberCount = 1;
		yield break;
	}


	// .............
	// #61: WakeUpAfterFail

	void passage61_Init()
	{
		this.Passages[@"WakeUpAfterFail"] = new StoryPassage(@"WakeUpAfterFail", new string[]{  }, passage61_Main);
	}

	IStoryThread passage61_Main()
	{
		yield return text("\tПридя в себя Алекс начала думать, что делать дальше.");
		yield return lineBreak();
		yield return text("\tЕдинственное, что оставалось девушке, это отправиться к воротам, ведущим в Небес" +
		    "ный район");
		yield return lineBreak();
		yield return link("Направиться ко входу", "GoToEntrance", null);
		yield break;
	}


	// .............
	// #62: AskForPlant

	void passage62_Init()
	{
		this.Passages[@"AskForPlant"] = new StoryPassage(@"AskForPlant", new string[]{  }, passage62_Main);
	}

	IStoryThread passage62_Main()
	{
		yield return text("\t- Роджер, ты заключил сделку с одним человеком на доставку клыка хищной кошки, а" +
		    " мне очень нужна его помощь! Можешь отдать мне его, а я отнесу заказчику.");
		yield return lineBreak();
		yield return text("\t- Ах, дорогая! Конечно же. Я его давно уже раздобыл, просто не успел занести. Де" +
		    "ржи его.");
		yield return lineBreak();
		yield return link("Вернуться к донуму", "ComeBack", null);
		yield break;
	}


	// .............
	// #63: ComeBack

	void passage63_Init()
	{
		this.Passages[@"ComeBack"] = new StoryPassage(@"ComeBack", new string[]{  }, passage63_Main);
	}

	IStoryThread passage63_Main()
	{
		yield return text("Донум благодарит тебя и рассказывает свою историю");
		yield return lineBreak();
		yield return text("Ставит значок ");
		yield return lineBreak();
		yield return link("Направиться ко входу", "GoToEntrance", null);
		yield break;
	}


	// .............
	// #64: WorkerYear

	void passage64_Init()
	{
		this.Passages[@"WorkerYear"] = new StoryPassage(@"WorkerYear", new string[]{  }, passage64_Main);
	}

	IStoryThread passage64_Main()
	{
		yield return text("\t- Сейчас 542 год от Великого Переселения.");
		yield return lineBreak();
		yield return link("Невозможно!!!", "YearWonder", null);
		yield break;
	}


	// .............
	// #65: BanditVillage

	void passage65_Init()
	{
		this.Passages[@"BanditVillage"] = new StoryPassage(@"BanditVillage", new string[]{  }, passage65_Main);
	}

	IStoryThread passage65_Main()
	{
		yield return text("\t- Эта деревня называется Инитиум, самое крайнее поселение Алиоса.");
		yield return lineBreak();
		yield return text("\t\"Ага, хорошо, что я нахожусь хотя бы в своём мире, но вот деревень не существует" +
		    " уже много сотен лет\".");
		yield return lineBreak();
		yield return link("Какой сейчас год", "BanditYear", null);
		yield break;
	}


}