/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: storytry.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @storytry: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@storytry()
	{
		this.StartPassage = "start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: start

	void passage1_Init()
	{
		this.Passages[@"start"] = new StoryPassage(@"start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Первый шаг.");
		yield return lineBreak();
		yield return link("firstA", "firstA", null);
		yield return lineBreak();
		yield return link("firstB", "firstB", null);
		yield return lineBreak();
		yield return link("firstC", "firstC", null);
		yield break;
	}


	// .............
	// #2: firstA

	void passage2_Init()
	{
		this.Passages[@"firstA"] = new StoryPassage(@"firstA", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Второй шаг A.");
		yield return lineBreak();
		yield return link("thirdAA", "thirdAA", null);
		yield return lineBreak();
		yield return link("thirdAB", "thirdAB", null);
		yield break;
	}


	// .............
	// #3: firstB

	void passage3_Init()
	{
		this.Passages[@"firstB"] = new StoryPassage(@"firstB", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Второй шаг Б.");
		yield return lineBreak();
		yield return link("thirdBA", "thirdBA", null);
		yield break;
	}


	// .............
	// #4: firstC

	void passage4_Init()
	{
		this.Passages[@"firstC"] = new StoryPassage(@"firstC", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Второй шаг С.");
		yield return lineBreak();
		yield return link("Death", "Death", null);
		yield break;
	}


	// .............
	// #5: thirdAA

	void passage5_Init()
	{
		this.Passages[@"thirdAA"] = new StoryPassage(@"thirdAA", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Третий шаг из А в А.]");
		yield return lineBreak();
		yield return link("Win", "Win", null);
		yield break;
	}


	// .............
	// #6: thirdAB

	void passage6_Init()
	{
		this.Passages[@"thirdAB"] = new StoryPassage(@"thirdAB", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Третий шаг из А в B");
		yield return lineBreak();
		yield return link("result", "result", null);
		yield break;
	}


	// .............
	// #7: Death

	void passage7_Init()
	{
		this.Passages[@"Death"] = new StoryPassage(@"Death", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Смерть");
		yield break;
	}


	// .............
	// #8: Win

	void passage8_Init()
	{
		this.Passages[@"Win"] = new StoryPassage(@"Win", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Победа");
		yield break;
	}


	// .............
	// #9: thirdBA

	void passage9_Init()
	{
		this.Passages[@"thirdBA"] = new StoryPassage(@"thirdBA", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Третий шаг из Б в A");
		yield return lineBreak();
		yield return link("result", "result", null);
		yield break;
	}


	// .............
	// #10: result

	void passage10_Init()
	{
		this.Passages[@"result"] = new StoryPassage(@"result", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("результаты.");
		yield return lineBreak();
		yield return link("Win", "Win", null);
		yield break;
	}


}